# -*- mode: ruby -*-

box = "generic/ubuntu1804"
ram = "65536"
hostname = "wpia-ncov-dev"
mac = "00:15:5d:1a:84:07"
cpus = 10

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.network "public_network", bridge: "External Switch", auto_config: true
  config.vm.provider :hyperv do |hyperv|
    hyperv.mac = mac
    hyperv.vmname = hostname
    hyperv.cpus = cpus
    hyperv.maxmemory = ram
    hyperv.memory = "65536"
    hyperv.auto_start_action = "StartIfRunning"
    hyperv.auto_stop_action = "Save"
  end
  config.vm.hostname = hostname
  config.vm.provision :shell, path: "../common/setup.sh",
		                                  env: {"hostname" => hostname}
  config.vm.provision :shell, path: "../common/setup-docker.sh"
  config.vm.provision :shell, path: "../common/setup-ssh-keys.sh", run: "always",
                              args: ["richfitz", "weshinsley"]
end
