agents = [
  { :hostname => 'wpia-shiny-dev-worker1', :mac => "00:15:5d:1a:84:38", :cpus => 2},
  { :hostname => 'wpia-shiny-dev-worker2', :mac => "00:15:5d:1a:84:37", :cpus => 2},

]

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.network "public_network", bridge: "External Switch", auto_config: true

  agents.each do |agent|
    config.vm.define agent[:hostname] do |agent_config|
      agent_config.vm.provider :hyperv do |hyperv|
        hyperv.mac = agent[:mac]
        hyperv.vmname = agent[:hostname]
        hyperv.cpus = agent[:cpus] || 2
        hyperv.maxmemory = agent[:ram] || ram
        hyperv.memory = agent[:ram] || ram
        hyperv.auto_start_action = "StartIfRunning"
        hyperv.auto_stop_action = "Save"
      end
      agent_config.vm.hostname = agent[:hostname]
      config.vm.provision :shell, path: "../common/setup-ssh-keys.sh", run: "always",
                              args: ["richfitz", "weshinsley", "EmmaLRussell", "absternator"]

        end
  end
end