# -*- mode: ruby -*-

Vagrant.require_version ">= 2.2.10"

box = "generic/ubuntu2204"
gateway = "14.0.0.1"
ram = "16384"
agents = [
  { :hostname => 'hermod-1', :ip => '14.0.0.21', :mac => "00:15:5d:1a:84:34", :cpus => 2},
  { :hostname => 'hermod-2', :ip => '14.0.0.22', :mac => "00:15:5d:1a:84:35", :cpus => 2},
]

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.network "public_network", bridge: "NATSwitch", auto_config: false

  agents.each do |agent|
    config.vm.define agent[:hostname] do |agent_config|
      agent_config.vm.provider :hyperv do |hyperv|
        hyperv.mac = agent[:mac]
        hyperv.vmname = agent[:hostname]
        hyperv.cpus = agent[:cpus] || 2
        hyperv.maxmemory = agent[:ram] || ram
        hyperv.memory = agent[:ram] || ram
        hyperv.auto_start_action = "StartIfRunning"
        hyperv.auto_stop_action = "Save"
      end
      agent_config.vm.hostname = agent[:hostname]
      agent_config.vm.provision :shell, path: "./vm_scripts/setup-network.sh",
                                                  env: {"IP" => agent[:ip], "GW" => gateway}

        end
  end
end
